FROM python:3.14.4-slim

COPY --from=ghcr.io/astral-sh/uv:0.11.7 /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=0 \
    PATH="/src/.venv/bin:$PATH"

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY pyproject.toml uv.lock .python-version ./

RUN uv sync --locked --no-dev --no-install-project
RUN useradd -s /bin/bash admin

ENV TZ="Europe/Berlin"

RUN mkdir -p /src/grb_files

COPY ./crawler/nuts_mapper.py ./crawler/dwd.py ./crawler/common ./crawler/__init__.py /src/
COPY ./crawler/data/lat_coordinates.npy /src/data/
COPY ./crawler/data/lon_coordinates.npy /src/data/
COPY ./crawler/data/plz_matrix.npy /src/data/
COPY ./crawler/shapes /src/shapes

RUN chown -R admin /src

USER admin
WORKDIR /

CMD ["python", "-m", "src.dwd"]
