- name: Permanently disable cockpit service
  ansible.posix.firewalld:
    zone: public
    service: cockpit
    state: disabled
    permanent: true
    immediate: true

- name: Permit traffic in default zone for dhcpv6-client service
  ansible.posix.firewalld:
    zone: public
    service: dhcpv6-client
    permanent: true
    state: enabled
    immediate: true

- name: Permit traffic in default zone for ms-wbt (remote desktop) service
  ansible.posix.firewalld:
    zone: public
    service: ms-wbt
    permanent: true
    state: enabled
    immediate: true

- name: Permit traffic in default zone for ssh service
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: true
    state: enabled
    immediate: true
