- name: OEDS ACME certs
  hosts: oeds
  remote_user: root
  vars:
    oeds_certbot_package_state: present
  tasks:
  - name: Install certbot
    ansible.builtin.dnf:
      name:
        - certbot
      state: "{{ oeds_certbot_package_state }}"
  - name: Check acme4netvs directory
    ansible.builtin.stat:
      path: "/usr/libexec/acme4netvs"
    register: libdir
  - name: Create acme4netvs directory
    ansible.builtin.file:
      path: "/usr/libexec/acme4netvs"
      state: directory
      mode: 0755
      owner: root
      group: root
    when: not libdir.stat.exists
  - name: Install acme4netvs certbot lib
    ansible.builtin.unarchive:
      src: "https://gitlab.kit.edu/kit/kit-ca/acme/acme4netvs/-/releases/v0.8.3/downloads/acme4netvs_certbot_linux_amd64.tar.gz"
      dest: /usr/libexec/acme4netvs
      remote_src: yes
  - name: Check NetDB config directory
    ansible.builtin.stat:
      path: "/root/.config"
    register: confdir
  - name: Create NetDB config directory
    ansible.builtin.file:
      path: "/root/.config"
      state: directory
    when: not confdir.stat.exists
  - name: Install NetDB Client config
    ansible.builtin.copy:
      src: "/opt/ansible/resources/netdb_client.ini"
      dest: "/root/.config/netdb_client.ini"
  - name: Run certbot cert request
    ansible.builtin.shell: |
      certbot certonly --manual --manual-auth-hook /usr/libexec/acme4netvs/certbot_netvs_auth_hook --manual-cleanup-hook /usr/libexec/acme4netvs/certbot_netvs_cleanup_hook --preferred-challenge=dns -d {{ ansible_host }}
  - name: Enable cert renewal
    ansible.builtin.systemd_service:
      name: certbot-renew.timer
      enabled: true
      daemon_reload: true
      daemon-reexec: true
