---
- import_playbook: oeds-packages.yml

- import_playbook: oeds-docker-config.yml
  vars:
    oeds_enable_crawlers: true

- import_playbook: oeds-firewalld.yml
- import_playbook: oeds-certs.yml
- import_playbook: oeds-nginx.yml

- import_playbook: oeds-smoke-test.yml
  vars:
    oeds_expect_crawler_admin: true

