- name: OEDS SELinux config
  hosts: oeds
  become: true
  tasks:
  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    ansible.posix.selinux:
      policy: targeted
      state: permissive
